apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs-csi
  namespace: argocd
spec:
  project: foundationlayer
  source:
    repoURL: 'https://github.com/celigo/foundational-layers-helm-values'
    path: aws-ebs-csi-driver
    targetRevision: HEAD
    helm:
      releaseName: aws-ebs-csi-driver
      valueFiles:
        - values.yaml      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated: {}
